[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project]
name = "camino-pharmacy-dashboard"
version = "0.1.0"
description = "A Dash dashboard for pharmacy data served by the Camino datalake"
requires-python = ">=3.13"
dependencies = [
  "dash>=2.17.0",              # dashboard framework
  "dash-bootstrap-components", # bootstrap components for nicer looking webpages
  "pandas",                    # for dataframes
  "plotly",                    # for plots
  "duckdb",                    # for connecting to the Camino datalake
  "gunicorn",                  # production WSGI server for running the dashboard
]

[project.scripts]
dev-dashboard = "app.main:app.run"

[dependency-groups]
dev = [
  "prek>=0.5.4",   # linting
  "dash[testing]", # uses selenium for some webdriver testing
  "pytest",
  "selenium>4.6",
  # ^^ already included in dash[testing], but we need a newer
  # version to automatically get the webdriver this forces dash to be a
  # prerelease version. When dash updates to the new selenium we can delete
  # this and just pin dash minimum verison.
]
